version: "2"

networks:
  api-network:
    driver: bridge

services:
  api:
    env_file: .env
    build: .
    ports:
      - "3060:3060"
    networks:
      - api-network
    depends_on:
      - mongo
      - redis

  mongo:
    image: 'bitnami/mongodb:latest'
    env_file: .env
    ports:
      - "27019:27017"
    environment:
      - MONGODB_USERNAME=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_DATABASE=$MONGODB_DATABASE
      - MONGODB_ROOT_PASSWORD=$MONGODB_PASSWORD
    # volumes:
    #   - "mongo_data:/bitnami/mongodb"
    networks:
      - api-network

  redis:
    image: 'bitnami/redis:latest'
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - api-network
    volumes:
      - /var/data/redis

volumes:
  mongo_data:
